FROM cicca/anaconda:base
MAINTAINER Rick Moore

RUN apt-get update && apt-get install -y vim rsync
RUN mkdir -p /opt/tool_pkg
RUN mkdir -p /app_data
COPY tools/20160826_grapehard /opt/tool_pkg
COPY tools/.bashrc /
ENV PYTHONPATH=/opt/tool_pkg:$PYTHONPATH

EXPOSE 20007
CMD [ "/bin/bash" ]
